sudo: false
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
branches:
  only:
  - master
  - develop
env:
  - DJANGO_DEP=django22
  - DJANGO_DEP=djangomaster
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_DEP=djangomaster
  allow_failures:
    - python: "3.6"
      env: DJANGO_DEP=djangomaster
    - python: "3.7"
      env: DJANGO_DEP=djangomaster
install:
  - pip install tox
script: tox -e "py$(echo ${TRAVIS_PYTHON_VERSION} | tr -d .)-$DJANGO_DEP"

cache: pip
